# Generated by Django 4.2.7 on 2023-11-24 20:37

import app_products.models.comment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[app_products.models.comment.validate_iranian_phone_number]),
        ),
    ]
